-- Run after setup.sql. Imports the exact 70 supplied snack names as Common / weight 50.
with c as(select id from creators where slug='pretty-massacure'), names(name) as(values
  ('Popcorn'),
  ('Sun Chips'),
  ('Sour Cream and Cheddar chips'),
  ('Oreos'),
  ('Goldfish'),
  ('a Monster'),
  ('Doritos'),
  ('Pretzels'),
  ('Skittles'),
  ('Beaver nuggets'),
  ('a Hershey bar'),
  ('Girl Scout cookies'),
  ('a Chocolate easter bunny'),
  ('cotton candy'),
  ('a funnel cake'),
  ('deep fried butter'),
  ('deep fried Oreos'),
  ('dip in dots'),
  ('deep fried ice cream'),
  ('a Choco taco'),
  ('a banana split'),
  ('beignets'),
  ('a s''more'),
  ('Flaming fire flakes'),
  ('deep fried snickers'),
  ('deep fried twinkie'),
  ('a chocolate covered banana'),
  ('fudge'),
  ('French fries'),
  ('Mozzarella sticks'),
  ('Pickles'),
  ('a Slim Jim'),
  ('Jerky'),
  ('sunflower seeds'),
  ('a Kit Kat'),
  ('Trail mix'),
  ('a Snickers'),
  ('Peanut butter crackers'),
  ('chocolate covered cherries'),
  ('chocolate covered raisins'),
  ('gummy dicks'),
  ('gummy boobs'),
  ('Milk duds'),
  ('Mike n Ikes'),
  ('cereal'),
  ('sweet tart ropes'),
  ('chocolate chip cookies'),
  ('Cotton Candy gummy dicks'),
  ('a Twix'),
  ('Twix ice cream'),
  ('Cheez its'),
  ('Flaming hot Cheetos'),
  ('Sour Patch Kids'),
  ('a Honey Bun'),
  ('M & M''s'),
  ('Nerds Gummy Clusters'),
  ('a Reese''s Peanut Butter Cups'),
  ('Grandma''s Cookies'),
  ('a KIND granola bar'),
  ('a Pop Tart'),
  ('a Butterfinger'),
  ('a CRUNCH bar'),
  ('a Milky way'),
  ('NutterButters'),
  ('a Almond Joy'),
  ('a Mounds'),
  ('Chex Mix'),
  ('Buggles'),
  ('Takis'),
  ('a Rice Krispies Treat')
)
insert into snacks(creator_id,name,rarity,category,weight,enabled)
select c.id,n.name,'Common','Snack',50,true from c cross join names n
where not exists(select 1 from snacks s where s.creator_id=c.id and lower(s.name)=lower(n.name));

select count(*) as pretty_snack_count from snacks s join creators c on c.id=s.creator_id where c.slug='pretty-massacure' and not s.archived;
