/* Shared Snack Vault overlay adapter. No secrets are stored in browser code. */
(function(){
const params=new URLSearchParams(location.search);const channel=(params.get('channel')||'underscorepower').toLowerCase().replace(/[^a-z0-9_]/g,'');
const demo=params.get('demo')==='1';const api=params.get('api')||'';const poll=Math.max(2000,Number(params.get('poll'))||4000);
const sample={id:'demo-1',username:'underscorepower',snack:'Doritos Nacho Cheese',emoji:'🌮',rarity:'Legendary',total:12,items:[{name:'Doritos',emoji:'🌮',count:3},{name:'Takis',emoji:'🌶️',count:2},{name:'Reese’s',emoji:'🍫',count:1}],leaders:[{name:'underscorepower',count:42},{name:'SunshineJul',count:31},{name:'SirDeko',count:24}],timestamp:new Date().toISOString()};
let previous=null;function normalize(raw){let d=raw?.event||raw?.latest||raw?.data||raw||{};return {id:String(d.id||d.event_id||d.pull_id||d.timestamp||''),username:String(d.username||d.user||d.viewer||'Viewer'),snack:String(d.snack?.name||d.snack_name||d.snack||d.item||'Mystery Snack'),emoji:String(d.snack?.emoji||d.emoji||'🍬'),rarity:String(d.rarity||d.snack?.rarity||'Common'),total:Number(d.total||d.count||0),items:Array.isArray(d.items)?d.items:[],leaders:Array.isArray(d.leaders)?d.leaders:[],timestamp:d.timestamp||''};}
function dispatch(d){document.dispatchEvent(new CustomEvent('snackvault:update',{detail:d}));}
if(demo){dispatch(sample);setTimeout(()=>dispatch(sample),100);setInterval(()=>{sample.id='demo-'+Date.now();sample.snack=['Doritos Nacho Cheese','Takis Fuego','Reese’s Cups','Sour Patch Kids'][Math.floor(Math.random()*4)];sample.emoji=['🌮','🌶️','🍫','🍭'][Math.floor(Math.random()*4)];sample.rarity=['Common','Rare','Epic','Legendary'][Math.floor(Math.random()*4)];dispatch(sample)},12000);return;}
if(!api){document.dispatchEvent(new CustomEvent('snackvault:unconfigured'));return;}
async function fetchUpdate(){try{const url=new URL(api,location.href);url.searchParams.set('channel',channel);const r=await fetch(url,{cache:'no-store',credentials:'omit'});if(!r.ok)throw new Error('HTTP '+r.status);const d=normalize(await r.json());if(d.id&&d.id!==previous){previous=d.id;dispatch(d)}}catch(e){console.warn('[Snack Vault overlay]',e.message)}}fetchUpdate();setInterval(fetchUpdate,poll);
window.SnackVaultOverlay={channel,demo,api};
})();